export const PLAYER_IMAGES = {
  "Kylian Mbappé": "/players/kylian-mbappe.webp",
  "Michael Olise": "/players/michael-olise.webp",
  "Jude Bellingham": "/players/jude-bellingham.webp",
  "Harry Kane": "/players/harry-kane.webp",
  "Lamine Yamal": "/players/lamine-yamal.webp",
  Pedri: "/players/pedri.webp",
  "Vinícius Júnior": "/players/vinicius-junior.webp",
  Raphinha: "/players/raphinha.webp",
  "Lionel Messi": "/players/lionel-messi.webp",
  "Julián Álvarez": "/players/julian-alvarez.webp",
  "Bruno Fernandes": "/players/bruno-fernandes.webp",
  "Cristiano Ronaldo": "/players/cristiano-ronaldo.webp",
  "Nuno Mendes": "/players/nuno-mendes.webp",
  "Florian Wirtz": "/players/florian-wirtz.webp",
  "Jamal Musiala": "/players/jamal-musiala.webp",
  "Virgil van Dijk": "/players/virgil-van-dijk.webp",
  "Achraf Hakimi": "/players/achraf-hakimi.webp",
  "Erling Haaland": "/players/haaland.webp",
  "Federico Valverde": "/players/federico-valverde.webp",
  "Kevin De Bruyne": "/players/kevin-de-bruyne.webp",
  "Luka Modrić": "/players/luka-modric.webp",
  "Sadio Mané": "/players/sadio-mane.webp",
  "Luis Díaz": "/players/luis-diaz.webp",
};
